[package]
name = "hindmarsh-rose-v2-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rtsyn_plugin = { path = "../../Desktop/stuff/uni/master/TFM/rtsyn-plugin" }
serde_json = "1"

[lib]
crate-type = ["cdylib"]
